rpc:
  httpUrl: https://api.mainnet-beta.solana.com
  wsUrl: wss://api.mainnet-beta.solana.com
  connectionTimeout: 30000
  commitment: confirmed
  reconnectPolicy:
    maxRetries: 5
    baseDelay: 1000
    maxDelay: 60000
supportedDexes:
  - name: Raydium
    programId: 675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8
    instructions:
      newPoolCreation: initialize2
      swap: swap
      addLiquidity: addLiquidity
      removeLiquidity: removeLiquidity
    enabled: true
    priority: 1
  - name: Orca
    programId: 9W959DqEETiGZocYWCQPaJ6sBmUzgfxXfqGeTEdp3aQP
    instructions:
      newPoolCreation: createPool
      swap: swap
    enabled: false
    priority: 2
wallet:
  keypairPath: ./keys/trading-wallet.json
  riskPercent: 5
  maxTotalRiskPercent: 20
  confirmationRequired: false
  excludedTokens: []
  hardwareWallet:
    enabled: false
    defaultDerivationPath: m/44'/501'/0'/0'
    timeout: 30000
    requireConfirmation: true
    blindSigning: false
    autoConnect: false
    reconnectAttempts: 3
    reconnectDelay: 2000
tradeConfig:
  minLiquidityUsd: 1000
  maxSlippagePercent: 2
  gasLimit: 0.01
  defaultTradeAmountUsd: 100
  maxTradeAmountUsd: 1000
  minTokenPrice: 0.000001
  maxTokenSupply: 1000000000000
  maxHoldingTimeMinutes: 1440
  requiredBaseTokens:
    - So11111111111111111111111111111111111111112
    - EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
  minPoolAgeSeconds: 5
exitStrategies:
  - type: profit
    name: Default Profit Strategy
    description: Exit when profit reaches target percentage
    enabled: true
    params:
      profitPercentage: 50
      trailingStopPercent: 5
  - type: time
    name: Time-based Exit
    description: Exit after specified time has passed
    enabled: true
    params:
      timeMinutes: 60
  - type: loss
    name: Stop Loss
    description: Exit if loss reaches specified percentage
    enabled: true
    params:
      lossPercentage: 20
  - type: liquidity
    name: Liquidity Protection
    description: Exit if liquidity drops below threshold
    enabled: true
    params:
      minLiquidityUsd: 500
      percentOfInitial: 50
  - type: developer-activity
    name: Dev Wallet Monitor
    description: Exit if developer sells tokens
    enabled: true
    params:
      monitorDeveloperWallet: true
      exitOnSellPercentage: 10
  - type: trailing-stop
    name: Trailing Stop Loss
    description: Dynamic stop loss that trails behind the highest price
    enabled: false
    params:
      initialStopPercent: 15
      trailPercent: 10
      activationPercent: 20
      maxTrailAmount: 50
  - type: volatility-stop
    name: Volatility-Adjusted Stop
    description: Stop loss that adjusts based on price volatility
    enabled: false
    params:
      baseStopPercent: 15
      volatilityMultiplier: 0.5
      lookbackPeriodMinutes: 30
      minStopPercent: 10
      maxStopPercent: 25
  - type: volume-based
    name: Volume Exit Strategy
    description: Exit based on trading volume changes
    enabled: false
    params:
      minVolumeUsd: 1000
      volumeDropThresholdPercent: 70
      lookbackPeriodMinutes: 15
      exitOnVolumeSpike: true
      volumeSpikeMultiplier: 5
  - type: multi-condition
    name: Combined Exit Strategy
    description: Exit when multiple conditions are met
    enabled: false
    params:
      operator: OR
      priority: HIGHEST_URGENCY
      conditions:
        - type: profit
          enabled: true
          params:
            profitPercentage: 30
        - type: trailing-stop
          enabled: true
          params:
            initialStopPercent: 20
            trailPercent: 15
            activationPercent: 25
  - type: partial-exit
    name: Staged Exit Strategy
    description: Exit positions in stages based on different conditions
    enabled: false
    params:
      stages:
        - triggerCondition:
            type: profit
            enabled: true
            params:
              profitPercentage: 25
          exitPercentage: 30
        - triggerCondition:
            type: profit
            enabled: true
            params:
              profitPercentage: 50
          exitPercentage: 50
        - triggerCondition:
            type: profit
            enabled: true
            params:
              profitPercentage: 100
          exitPercentage: 100
      minStageGapPercent: 5
database:
  path: ./data/liquid-snipe.db
  backupIntervalHours: 24
  maxBackups: 7
  logToDatabase: true
  pruneEventsOlderThanDays: 30
notifications:
  enabled: false
  telegram:
    enabled: false
    notifyOnTrade: true
    notifyOnPosition: true
    notifyOnError: true
  discord:
    enabled: false
    notifyOnTrade: true
    notifyOnPosition: true
    notifyOnError: true
marketMonitoring:
  enabled: true
  priceVolatilityThreshold: 25
  volumeSpikeMultiplier: 3
  liquidityDropThreshold: 30
  monitoringInterval: 30000
  historicalDataWindow: 60
  circuitBreakerConfig:
    failureThreshold: 3
    successThreshold: 5
    timeout: 60000
    monitoringPeriod: 300000
riskManagement:
  enabled: true
  maxTotalExposure: 10000
  maxSinglePositionSize: 1000
  maxPortfolioPercentage: 50
  maxConcentrationRisk: 30
  maxDailyLoss: 500
  maxDrawdown: 20
  volatilityMultiplier: 0.5
  correlationThreshold: 0.7
  rebalanceThreshold: 10
  riskAssessmentInterval: 60000
  emergencyExitThreshold: 15
activeStrategy: default
logLevel: info
pollingInterval: 1000
dryRun: false
verbose: false
disableTui: false
